CREATE DATABASE IF NOT EXISTS AULA_21_09;
USE AULA_21_09;
DROP DATABASE AULA_21_09;

CREATE TABLE MUSICA (
	id INT PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(100) NOT NULL,
	duracao DECIMAL(5,4) NOT NULL,
	compositor VARCHAR(100) NOT NULL,
	album VARCHAR(100) NOT NULL
);

SELECT * FROM MUSICA;